<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-red">
        <div class="inner">
          <h3>$1990</h3>
          <p><?php echo __("Credit Amount")?></p>
        </div>
        <div class="icon">
          <i class="ion ion-card"></i>
        </div>
      </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-yellow">
        <div class="inner">
          <h3>$15035</h3>
          <p><?php echo __("Lifetime Sales")?></p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
      </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-green">
        <div class="inner">
          <h3>$98</h3>
          <p><?php echo __("Average Orders")?></p>
        </div>
        <div class="icon">
          <i class="ion ion-stats-bars"></i>
        </div>
      </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3>3454</h3>
          <p><?php echo __("Total Products")?></p>
        </div>
        <div class="icon">
          <i class="ion ion-cube"></i>
        </div>
      </div>
    </div><!-- ./col -->
</div><!-- /.row -->


<div class="row row-grap">
    <div class="col-md-8">
        <div class="nav-tabs-custom">
            <!-- Tabs within a box -->
            <ul class="nav nav-tabs pull-right">
              <li><a href="#amount-chart" data-toggle="tab"><?php echo __("Amount")?></a></li>
              <li class="active"><a class="active" href="#order-chart" data-toggle="tab"><?php echo __("Orders")?></a></li>
              <li class="pull-left header"><i class="fa fa-inbox"></i> <?php echo __("Sales")?></li>
            </ul>
            <div class="tab-content no-padding">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="order-chart" style="position: relative; height: 300px;"></div>
              <div class="chart tab-pane" id="amount-chart" style="position: relative; height: 300px;"></div>
            </div>
        </div><!-- /.nav-tabs-custom -->

        <!-- TABLE: LATEST ORDERS -->
        <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Latest Orders</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table class="table no-margin">
                  <thead>
                    <tr>
                      <th>Order ID</th>
                      <th>Item</th>
                      <th>Status</th>
                      <th>Popularity</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR9842</a></td>
                      <td>Call of Duty IV</td>
                      <td><span class="label label-success">Shipped</span></td>
                      <td><div class="sparkbar" data-color="#00a65a" data-height="20">90,80,90,-70,61,-83,63</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR1848</a></td>
                      <td>Samsung Smart TV</td>
                      <td><span class="label label-warning">Pending</span></td>
                      <td><div class="sparkbar" data-color="#f39c12" data-height="20">90,80,-90,70,61,-83,68</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR7429</a></td>
                      <td>iPhone 6 Plus</td>
                      <td><span class="label label-danger">Delivered</span></td>
                      <td><div class="sparkbar" data-color="#f56954" data-height="20">90,-80,90,70,-61,83,63</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR7429</a></td>
                      <td>Samsung Smart TV</td>
                      <td><span class="label label-info">Processing</span></td>
                      <td><div class="sparkbar" data-color="#00c0ef" data-height="20">90,80,-90,70,-61,83,63</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR1848</a></td>
                      <td>Samsung Smart TV</td>
                      <td><span class="label label-warning">Pending</span></td>
                      <td><div class="sparkbar" data-color="#f39c12" data-height="20">90,80,-90,70,61,-83,68</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR7429</a></td>
                      <td>iPhone 6 Plus</td>
                      <td><span class="label label-danger">Delivered</span></td>
                      <td><div class="sparkbar" data-color="#f56954" data-height="20">90,-80,90,70,-61,83,63</div></td>
                    </tr>
                    <tr>
                      <td><a href="pages/examples/invoice.html">OR9842</a></td>
                      <td>Call of Duty IV</td>
                      <td><span class="label label-success">Shipped</span></td>
                      <td><div class="sparkbar" data-color="#00a65a" data-height="20">90,80,90,-70,61,-83,63</div></td>
                    </tr>
                  </tbody>
                </table>
              </div><!-- /.table-responsive -->
            </div><!-- /.box-body -->
            <div class="box-footer clearfix">
              <a href="javascript::;" class="btn btn-sm btn-info btn-flat pull-left">Place New Order</a>
              <a href="javascript::;" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
            </div><!-- /.box-footer -->
        </div><!-- /.box -->
    </div>
    
    <div class="col-md-4">
        <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Browser Usage</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;"></div>
                </div><!-- /.row -->
            </div><!-- /.box-body -->
            <div class="box-footer no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="#">United States of America <span class="pull-right text-red"><i class="fa fa-angle-down"></i> 12%</span></a></li>
                <li><a href="#">India <span class="pull-right text-green"><i class="fa fa-angle-up"></i> 4%</span></a></li>
                <li><a href="#">China <span class="pull-right text-yellow"><i class="fa fa-angle-left"></i> 0%</span></a></li>
              </ul>
            </div><!-- /.footer -->
          </div><!-- /.box -->
          
          
          
          <!-- PRODUCT LIST -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Recently Added Products</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <ul class="products-list product-list-in-box">
                <li class="item">
                  <div class="product-img">
                    <img src="dist/img/default-50x50.gif" alt="Product Image">
                  </div>
                  <div class="product-info">
                    <a href="javascript::;" class="product-title">Samsung TV <span class="label label-warning pull-right">$1800</span></a>
                    <span class="product-description">
                      Samsung 32" 1080p 60Hz LED Smart HDTV.
                    </span>
                  </div>
                </li><!-- /.item -->
                <li class="item">
                  <div class="product-img">
                    <img src="dist/img/default-50x50.gif" alt="Product Image">
                  </div>
                  <div class="product-info">
                    <a href="javascript::;" class="product-title">Bicycle <span class="label label-info pull-right">$700</span></a>
                    <span class="product-description">
                      26" Mongoose Dolomite Men's 7-speed, Navy Blue.
                    </span>
                  </div>
                </li><!-- /.item -->
                <li class="item">
                  <div class="product-img">
                    <img src="dist/img/default-50x50.gif" alt="Product Image">
                  </div>
                  <div class="product-info">
                    <a href="javascript::;" class="product-title">Xbox One <span class="label label-danger pull-right">$350</span></a>
                    <span class="product-description">
                      Xbox One Console Bundle with Halo Master Chief Collection.
                    </span>
                  </div>
                </li><!-- /.item -->
                <li class="item">
                  <div class="product-img">
                    <img src="dist/img/default-50x50.gif" alt="Product Image">
                  </div>
                  <div class="product-info">
                    <a href="javascript::;" class="product-title">PlayStation 4 <span class="label label-success pull-right">$399</span></a>
                    <span class="product-description">
                      PlayStation 4 500GB Console (PS4)
                    </span>
                  </div>
                </li><!-- /.item -->
              </ul>
            </div><!-- /.box-body -->
            <div class="box-footer text-center">
              <a href="javascript::;" class="uppercase">View All Products</a>
            </div><!-- /.box-footer -->
          </div><!-- /.box -->
          
          
    </div>
</div>
<script>
require([
    'jquery',
    'jquery/ui',
    'raphael',
    'jquery/morris'
], function(jQuery, ui){
    console.log('Ready !');


    /* Morris.js Charts */
    // Sales chart
    var order = new Morris.Area({
      element: 'order-chart',
      resize: true,
      data: [
        {y: '2011 Q1', item1: 1},
        {y: '2011 Q2', item1: 0},
        {y: '2011 Q3', item1: 2},
        {y: '2011 Q4', item1: 5},
        {y: '2012 Q1', item1: 4},
        {y: '2012 Q2', item1: 3},
        {y: '2012 Q3', item1: 8},
        {y: '2012 Q4', item1: 2},
        {y: '2013 Q1', item1: 3},
        {y: '2013 Q2', item1: 4}
      ],
      xkey: 'y',
      ykeys: ['item1',],
      labels: ['Item 1'],
      lineColors: ['#a0d0e0'],
      hideHover: 'auto'
    });

    var amount = new Morris.Area({
        element: 'amount-chart',
        resize: true,
        data: [
          {y: '2011 Q1', item2: 2666},
          {y: '2011 Q2',item2: 2294},
          {y: '2011 Q3', item2: 1969},
          {y: '2011 Q4', item2: 3597},
          {y: '2012 Q1', item2: 1914},
          {y: '2012 Q2', item2: 4293},
          {y: '2012 Q3', item2: 3795},
          {y: '2012 Q4', item2: 5967},
          {y: '2013 Q1', item2: 4460},
          {y: '2013 Q2', item2: 5713}
        ],
        xkey: 'y',
        ykeys: ['item2'],
        labels: ['Item 2'],
        lineColors: ['#3c8dbc'],
        hideHover: 'auto'
      });
    //Fix for charts under tabs
    jQuery('.row-grap ul.nav a').on('shown.bs.tab', function () {
    	order.redraw();
        amount.redraw();
    });

    
    //Donut Chart
    var donut = new Morris.Donut({
      element: 'sales-chart',
      resize: true,
      colors: ["#3c8dbc", "#f56954", "#00a65a"],
      data: [
        {label: "Download Sales", value: 12},
        {label: "In-Store Sales", value: 30},
        {label: "Mail-Order Sales", value: 20}
      ],
      hideHover: 'auto'
    });
    

});
</script>