<?php
// @codingStandardsIgnoreFile

/** @var \Vnecoms\PageBuilder\Block\Section\DefaultSection $block */
?>

<section class="pb-section pb-section-feature8 row" id="<?php echo $block->getNameInLayout()?>">	
	<div class="col-md-6">
		<div class="pb-section-title">
            <?php echo $this->getChildHtml('title')?>
            <?php echo $this->getChildHtml('subtitle')?>
		</div>
		<?php echo $this->getChildHtml('description')?>
		<?php echo $this->getChildHtml('view_more')?>
	</div>
	<div class="col-md-6 pb-image-container">
		<?php echo $this->getChildHtml('image')?>
	</div>
</section>