<?php
// @codingStandardsIgnoreFile

/** @var \Vnecoms\PageBuilder\Block\Section\DefaultSection $block */
?>

<section class="pb-section pb-section-welcome1">
	<div class="row">
		<div class="col-md-9">
		    <div class="pb-welcome1-title-container">
		        <?php echo $block->getChildHtml('title_welcome')?>
		    </div>
		    <div class="pb-welcome1-content-container">
		        <div class="pb-welcome1-img">
		        	<?php echo $block->getChildHtml('image')?>
				</div>
				<?php echo $block->getChildHtml('description')?>
		    </div>
		</div>
		
		<div class="col-md-3 pb-chooseus1">
		    <div class="pb-welcome1-title-container">
		        <?php echo $block->getChildHtml('title_chooseus')?>
		    </div>
		    <div class="content-why">
		        <?php echo $block->getChildHtml('why_choose_us')?>
		    </div>
		</div>
	</div>
</section>