<div class="box">
    <div class="box-body">
        <div class="section-config active">
            <div class="entry-edit-head admin__collapsible-block box-header with-border">
                <span id=withdrawal-request class="entry-edit-head-link"></span>
                <i class="fa fa-bars"></i>
                <a class="box-title open" href="#withdrawal-request"><?php echo __('Withdrawal Request')?></a>
            </div>
            <fieldset class="config admin__collapsible-block" id="general_store_information">
                <legend>Store Information</legend>
                <div class="form-horizontal">
                    <table class="table table-striped"><tbody>
                        <tr>
                            <th><?php echo __('Payment Method')?></th>
                            <th><?php echo __('Description')?></th>
                            <th><?php echo __('Fee')?></th>
                        </tr>
                        <?php foreach($block->getWithdrawalMethods() as $method):?>
                        <tr>
                            <td><strong><a href="<?php echo $block->getWithdrawalUrl($method)?>"><?php echo $method->getTitle();?></a></strong></td>
                            <td>
                                <?php echo $method->getDescription();?>
                            </td>
                            <td><span class="badge bg-yellow"><?php echo $method->getFee();?></span></td>
                        </tr>
                        <?php endforeach;?>
                  </tbody></table>
                </div>
            </fieldset>
        </div>
    </div>
</div>