<?php
/** @var Simi\Simicustomize\Block\Adminhtml\Service\Form\Field\Images $block */
?>

<div class="admin__field-label">
    <label>
        <span><?= $block->escapeHtml(__('All uploaded files')); ?></span>
    </label>
</div>
<div class="admin__field-control">
    <div class="admin__field-content">
        <table>
        <?php foreach($block->getFileUrls() as $key => $link): ?>
            <tr>
                <td><strong><?= "File ".($key+1) ?></strong></td>
                <td>
                    <?php $exploed = explode('.', $link); $ext = array_pop($exploed);  ?>
                    <?php if(in_array($ext, ['jpg', 'png', 'gif', 'jpeg'])): ?>
                        <img style="max-width: 275px" src="<?= $link ?>" alt="<?= $key ?>"/>
                    <?php else: ?>
                        <a href="<?= $link ?>"><?= __('Download') ?></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
