<div  id="ajaxlogin-login-window" class="login-window account-login ajaxloginphtml">
<form action="<?php echo $block->getUrl('mobilelogin/index/ajaxlogin') ?>" data-mage-init='{"validation": {}}' method="post" id="mobile-login-form" class="scaffold-form">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="updatepasssuccess success" id="updatepasssuccess">
        <span ><?php echo __("Password has been Updated Successfully.");?></span>
    </div>
    <div class="sendemail success"  id="sendemail_success">
    </div>
    <div class="emailpasswrong error1" id="emailpasswrong_error1">
        <span></span>
    </div>
    <div class="content">
        <ul class="form-list" id="form-list">
            <li>
                <div class="input-box">
                    <span  id="input-box-login"> <input type="text"  name="login[username]" value="" id="mobile-login-email" placeholder="<?php echo __('Email Address/Mobile Number *') ?>" class="input-text required-entry " title="<?php echo __('Email Address') ?>" > <span class="user-icon"></span> </span>
                </div>
                <div class="notice" id="notice1"><?php echo __("Mobile No. Without Country Code i.e 9898989898");?></div>
            </li>
            <li>
                <div class="input-box">
                    <span id="input-box-password"> <input type="password" name="login[password]" placeholder="<?php echo __('Password') ?>" class="input-text required-entry validate-password" id="mobile-login-pass" title="<?php echo __('Password') ?>" /><span class="pass-icon"></span></span>
                </div>
            </li>
        </ul>
    </div>
    <div class="<?php if($block->getTemplateImage()){echo 'buttons-set-ultimate';}else{ echo 'buttons-set';} ?>">
        <div class="register">
            <?php echo __("Don’t have an Account?");?> <a class="createlinking" href="#" id="register"><?php echo __("Register");?></a>
        </div>
        <div class="forogotlink">
            <a class="forgotlinking" href="#"><?php echo __("Forgot Password ?");?></a>
        </div>
    </div>
    <div class="loginlink">
        <button type="button" class="mobbtn primary" title="<?php echo __('Login') ?>" name="send" id="loginsubmit"><span><span><?php echo __('Login') ?></span></span></button>
        <div class="progress-indicator"  id="progress-indicator">
            <span class="please-wait" id="login-please-wait">
                <img src="<?php echo $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
            </span>
        </div>
    </div>
</form>
</div>