<?php

/** @var \Simi\Simistorelocator\Block\Adminhtml\Guide $block */

$userGuide = __('
	Magento Store Locator extension allows locating stores and getting directions with Google Map integrated:<br />
        1. To add/ import stores with location, time schedule and other information, go to <strong>Simicart</strong> -> <strong>Store Locator</strong> -> <strong>Manage Stores</strong>.<br />
        2. To set days off for store(s), go to <strong>Simicart</strong> -> <strong>Store Locator</strong> -> <strong>Manage Holidays</strong>.<br />
        3. To set days with special working time for store(s), go to <strong>Simicart</strong> -> <strong>Store Locator</strong> -> <strong>Manage Special Days</strong>.<br />
        4. To configure Store Locator extension, go to <strong>Simicart</strong> -> <strong>Store Locator</strong> -> <strong>Settings</strong>.
    ');
?>
<div class="fieldset ">
    <?php echo $userGuide ?>
</div>
