<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Vnecoms\Vendors\Block\Vendors\Page\Header */
?>

<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only"><?php __("Toggle navigation")?></span>
    </a>
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <?php echo $this->getChildHtml()?>
        </ul>
    </div>
</nav>