<?php 
/**
 * See \Vnecoms\VendorsCredit\Block\Vendors\Withdraw\History\View
 */
?>

<?php $withdrawal = $block->getWithdrawal();?>

<div class="box">
    <div class="box-body">
        <div class="active">
            <div class="entry-edit-head admin__collapsible-block box-header with-border">
                <span id=withdrawal-request class="entry-edit-head-link"></span>
                <i class="fa fa-bars"></i>
                <a class="box-title open" href="#withdrawal-request"><?php echo __('Withdrawal Request')?></a>
            </div>
            <fieldset class="config admin__collapsible-block" id="general_store_information">
                <legend><?php echo __('Withdrawal Request')?></legend>
                <div class="box-body form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Payment Method")?></label>
                        <div class="col-sm-6 control value">
                            <span class="control-text"><?php echo $block->getPaymentMethodTitle();?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Amount")?></label>
                        <div class="col-sm-6 control value">
                            <span class="control-text"><?php echo $block->formatBaseCurrency($withdrawal->getAmount());?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Fee")?></label>
                        <div class="col-sm-6 control value">
                            <span class="control-text"><?php echo $block->formatBaseCurrency($withdrawal->getFee());?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Net Amount")?></label>
                        <div class="col-sm-6 control value">
                            <span class="control-text"><?php echo $block->formatBaseCurrency($withdrawal->getNetAmount());?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Status")?></label>
                        <div class="col-sm-6 control value control-text">
                            <div class="label <?php echo $block->getStatusHtmlClass()?>"><?php echo $block->getStatusLabel()?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Created At")?></label>
                        <div class="col-sm-6 control value">
                            <div class="control-text"><?php echo $block->formatDate($withdrawal->getCreatedAt(), \IntlDateFormatter::MEDIUM,true);?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-5 control-label"><?php echo __("Updated At")?></label>
                        <div class="col-sm-6 control value">
                            <div class="control-text"><?php echo $block->formatDate($withdrawal->getUpdatedAt(), \IntlDateFormatter::MEDIUM,true);?></div>
                        </div>
                    </div>
                    <div class="form-group">
                    <?php foreach($block->getAdditionalInfo() as $info):?>
                        <div>
                            <label class="col-sm-5 control-label"><?php echo $info['label']?></label>
                            <div class="col-sm-6 control value control-text">
                                <?php echo $info['value']?$info['value']:'&nbsp;';?>
                            </div>
                        </div>
                    <?php endforeach;?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>