<?php

// @codingStandardsIgnoreFile

?>

<?php $value = $this->getValue(); ?>

<style>
    .heading-widget {
        font-size: <?php echo $value['header_font_size']?>px !important;
    <?php echo (isset($value['header_font_italic']) &&($value['header_font_italic'] == '1'))
    ? 'font-style:italic !important;' : ''?>
    <?php echo (isset($value['header_font_bold']) && ($value['header_font_bold'] == '1'))
    ? 'font-weight:bold !important;' : ''?>
    }

    .row-widget {
        font-size: <?php echo $value['row_font_size']?>px !important;
    <?php echo (isset($value['row_font_italic']) and $value['row_font_italic'] == '1')
    ? 'font-style:italic !important;' : ''?>
    <?php echo (isset($value['row_font_bold']) and $value['row_font_bold'] == '1')
    ? 'font-weight:bold !important;' : ''?>
    }
</style>
<table id="table" class="items" cellpadding="6" cellspacing="0">
    <thead>
    <tr>
        <?php $i = 0;?>
        <?php foreach($this->getColumn() as $_column):?>
            <th
                style="width:<?php echo $_column['width']?>px;"
                class="heading-widget header <?php echo $_column['option']?><?php if($i==0) echo ' first'?>">
                <?php echo $_column['title']?>
            </th>
            <?php $i++;?>
        <?php endforeach ?>
    </tr>
    </thead>
    <tbody>
    <?php $j = 0;?>
    <?php foreach($this->getItems() as $item):?>
        <tr class="<?php if($j%2==0) echo 'even'; else echo 'odd'; ?>">
            <?php foreach($this->getColumn() as $_column): ?>
                <?php if($_column['option'] == 'position'):?>
                    <td
                        style="width:<?php echo $_column['width']?>px;"
                        class="row-widget num">
                        <?php echo $j+1?>
                    </td>
                <?php elseif($_column['option'] == 'name'):?>
                    <td
                        style="width:<?php echo $_column['width']?>px;"
                        class="row-widget product">
                        <?php echo $item->getData('name')?>
                    </td>
                <?php elseif($_column['option'] == 'ves_custom'):?>
                    <td
                        style="width:<?php echo $_column['width']?>px;"
                        class="row-widget <?php echo $_column['option'] ?>">
                        <?php echo $item->getData($_column['custom']) ?>
                    </td>
                <?php else: ?>
                    <?php if($_column['option_choose'] == \Vnecoms\PdfPro\Model\Source\Widget\Optiontype::OPTION_TEXT):?>
                        <?php if(strpos($_column['option'], 'ves') !== false):?>
                            <td
                                style="width:<?php echo $_column['width']?>px;"
                                class="row-widget <?php echo $_column['option'] ?>">
                                <?php echo $item->getProduct()->getData(str_replace('ves_','',$_column['option'])) ?>
                            </td>
                        <?php else:?>
                            <td
                                style="width:<?php echo $_column['width']?>px;"
                                class="row-widget <?php echo $_column['option'] ?>">
                                <?php echo $item->getData($_column['option']) ?>
                            </td>
                        <?php endif ?>
                    <?php elseif($_column['option_choose'] == \Vnecoms\PdfPro\Model\Source\Widget\Optiontype::OPTION_IMAGE):?>
                        <td style="width:<?php echo $_column['width']?>px;"
                            class="row-widget <?php echo $_column['option'] ?>">
                            <img alt="<?php echo $_column['option'] ?>"
                                 width="<?php echo $_column['option_width']?>"
                                 height="<?php echo $_column['option_height']?>"
                                 src="<?php echo $item->getProduct()->getData(str_replace('ves_','',$_column['option'])) ?>" />
                        </td>
                    <?php endif ?>
                <?php endif ?>
            <?php endforeach ?>
        </tr>
        <?php if($item->getSubItems()):?>
            <?php foreach ($item->getSubItems() as $bundle):?>
                <tr class="<?php if($j%2==0) echo 'even'; else echo 'odd'; ?>">
                    <?php foreach($this->getColumn() as $_column): ?>
                        <?php if($_column['option'] == 'name'):?>
                            <td style="width:<?php echo $_column['width']?>px;" class="row-widget">
                                <div style="margin-left:20px;">
                                    <strong><?php echo $bundle->getLabel() ?></strong>
                                    <div class="product-options">
                                        <?php echo $bundle->getValue() ?>
                                    </div>
                                </div>
                            </td>
                        <?php elseif($_column['option'] == 'ves_custom'):?>
                            <td
                                style="width:<?php echo $_column['width']?>px;"
                                class="row-widget <?php echo $_column['option'] ?>">
                                <?php echo $bundle->getData($_column['custom']) ?>
                            </td>
                        <?php else: ?>
                            <?php if($_column['option_choose'] == \Vnecoms\PdfPro\Model\Source\Widget\Optiontype::OPTION_TEXT):?>
                                <?php if(strpos($_column['option'], 'ves') !== false):?>
                                    <td
                                        style="width:<?php echo $_column['width']?>px;"
                                        class="row-widget <?php echo $_column['option'] ?>">
                                        <?php echo $bundle->getProduct()->getData(str_replace('ves_','',$_column['option'])) ?>
                                    </td>
                                <?php else:?>
                                    <td
                                        style="width:<?php echo $_column['width']?>px;"
                                        class="row-widget <?php echo $_column['option'] ?>">
                                        <?php echo $bundle->getData($_column['option']) ?>
                                    </td>
                                <?php endif ?>
                            <?php elseif($_column['option_choose'] == \Vnecoms\PdfPro\Model\Source\Widget\Optiontype::OPTION_IMAGE):?>
                                <td
                                    style="width:<?php echo $_column['width']?>px;"
                                    class="row-widget <?php echo $_column['option'] ?>">
                                    <img alt="<?php echo $_column['option'] ?>"
                                         width="<?php echo $_column['option_width']?>"
                                         height="<?php echo $_column['option_height']?>"
                                         src="<?php echo $bundle->getProduct()->getData(str_replace('ves_','',$_column['option'])) ?>" />
                                </td>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endforeach ?>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
        <?php foreach($item->getOptions() as $option):?>
            <tr class="product-options <?php if($j % 2):?>odd<?php else:?>even<?php endif;?>"><td colspan="<?php echo sizeof($this->getColumn())?>"><strong><?php echo $option->getLabel()?></strong> :<?php echo $option->getValue()?></td></tr>
        <?php endforeach;?>
        <?php $j++; ?>
    <?php endforeach ?>
    </tbody>
</table>