<div class="testimonials-container">
	<div class="owl-carousel owl-theme testimonials-slider" id="pb-<?php echo $block->getNameInLayout()?>-slider">
		<?php foreach($this->getFields() as $fieldId => $fieldData):?>
            <?php echo $block->getChildHtml($fieldId);?>
        <?php endforeach?>
	</div>
	<script type="text/javascript">
	 require([
        "jquery",
        "Vnecoms_PageBuilder/owlcarousel/owl.carousel",
     ], function($){
		 $('#pb-<?php echo $block->getNameInLayout()?>-slider').owlCarousel({
             nav: false,
             dots: true,
             responsive: {
                 0: {
                     items: 1
                 },
                 480: {
                     items: 1
                 },
                 768: {
                     items: 2
                 },
                 991: {
                     items: 3
                 },
                 1200: {
                     items: 3
                 }
             }
         });
	 });
	</script>
</div>