<?php
/**
 * Copyright © Vnecoms, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * dashboard
 *
 * @var $block \Vnecoms\VendorsDashboard\Block\Dashboard
 */
?>
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6 credit-amount">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3><?php echo $block->formatPrice($block->getCreditAmount())?></h3>
                <p><?php echo __("Credit Amount")?></p>
            </div>
            <div class="icon">
                <i class="ion ion-card"></i>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6 lifetime-sales">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3><?php echo $block->formatPrice($block->getLifetimeSales())?></h3>
                <p><?php echo __("Lifetime Sales")?></p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6 average-orders">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3><?php echo $block->formatPrice($block->getAverageOrders())?></h3>
                <p><?php echo __("Average Orders")?></p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6 total-products">
        <!-- small box -->
        <div class="small-box bg-purple">
            <div class="inner">
                <h3><?php echo $block->getTotalProducts()?></h3>
                <p><?php echo __("Total Products")?></p>
            </div>
            <div class="icon">
                <i class="ion ion-cube"></i>
            </div>
        </div>
    </div><!-- ./col -->
</div><!-- /.row -->

<div class="row row-grap">
    <div class="col-md-8">
        <?php echo $block->getChildHtml("dashboard_content")?>
    </div>

    <div class="col-md-4">
        <?php echo $block->getChildHtml('dashboard_right')?>
    </div>
</div>

<script>
    var URL_GRAPH = '<?php echo $block->getGraphUrl()?>';

    require([
        'jquery',
        'jquery/ui',
        'mage/translate',
        'jquery/raphael',
        'jquery/morris',
        'loader',
        'domReady!'
    ], function($, ui, $t) {
        function changeDiagramsPeriod(value) {
            var graphContainer = $('#vendor_dashboard_graph_content');
            graphContainer.trigger('processStart');

            var xLabels = getChartXLabels(value);

            $.ajax({
                url: URL_GRAPH,
                method: "POST",
                data: { period : value ,vendor_id:<?php echo $block->getVendor()->getId()?>},
                dataType: "json"
            }).done(function( response ) {
                graphContainer.trigger('processStop');
                if(response.ajaxExpired){
                    window.location = response.ajaxRedirect;
                    return;
                }
                window.ves_chart_data = response;
                drawTransactionChart(response.transaction_chart, xLabels);
                drawOrdersChart(response.order_chart, xLabels);
                drawAmountsChart(response.amount_chart,xLabels)

            });
        }
        /*Get chart XLabels*/
        function getChartXLabels(value) {
            if(typeof(value) == 'undefined') value = $("#transaction_period").val();
            var xLabels = '';
            switch (value) {
                case '24h':
                    xLabels = 'hour';
                    break;
                case '7d':
                case '1m':
                    xLabels = 'day';
                    break;
                case '1y':
                case '2y':
                    xLabels = 'month';
                    break;
            }

            return xLabels;
        }

        /*Draw transaction chart*/
        function drawTransactionChart(data, xLabels) {
            $('#transaction-chart').html('');
            if (data.size()) {
                Morris.Line({
                    element: 'transaction-chart',
                    resize: true,
                    parseTime: true,
                    xLabels: xLabels,
                    data: data,
                    xkey: 'y',
                    ykeys: ['received', 'spent'],
                    labels: ["<?php echo __('Credits Received') ?>","<?php echo __('Credits Spent') ?>"],
                    lineColors: ['#3C8DBC', '#F56954'],
                    hideHover: 'auto'
                });
            } else {
                $('#transaction-chart').html('<div class="dashboard-diagram-nodata"><span>' + $t('No Data Found') + '</span></div>')
            }
        }

        /*Draw order chart*/
        function drawOrdersChart(data, xLabels) {
            $('#orders-chart').html('');
            if (data.size()) {
                Morris.Area({
                    element: 'orders-chart',
                    resize: true,
                    parseTime: true,
                    xLabels: xLabels,
                    data: data,
                    xkey: 'y',
                    ykeys: ['order_num'],
                    labels: ["<?php echo __('Orders') ?>"],
                    lineColors: ['#3C8DBC'],
                    hideHover: 'auto'
                });
            } else {
                $('#orders-chart').html('<div class="dashboard-diagram-nodata"><span>' + $t('No Data Found') + '</span></div>')
            }
        }

        /*Draw order chart*/
        function drawAmountsChart(data, xLabels) {
            $('#amounts-chart').html('');
            if (data.size()) {
                Morris.Area({
                    element: 'amounts-chart',
                    resize: true,
                    parseTime: true,
                    xLabels: xLabels,
                    data: data,
                    xkey: 'y',
                    ykeys: ['amount'],
                    labels: ["<?php echo __('Amounts') ?>"],
                    lineColors: ['#F56954'],
                    hideHover: 'auto'
                });
            } else {
                $('#orders-chart').html('<div class="dashboard-diagram-nodata"><span>' + $t('No Data Found') + '</span></div>')
            }
        }

        changeDiagramsPeriod($("#transaction_period").val());

        $('#vendor_dashboard_graph').on("tabsactivate", function(event, ui) {
            var xLabels = getChartXLabels();
            drawTransactionChart(window.ves_chart_data.transaction_chart,xLabels);
            drawOrdersChart(window.ves_chart_data.order_chart,xLabels);
            drawAmountsChart(window.ves_chart_data.amount_chart,xLabels);
        });

        $('#vendor_dashboard_sellerstate').on("tabsbeforeload", function(event, ui) {
            var newPanel = $(ui.panel);
            newPanel.trigger('processStart');
        });
        $('#vendor_dashboard_sellerstate').on("tabsload", function(event, ui) {
            var panel = $(ui.panel);
            panel.trigger('processStop');
        });

        window.changeDiagramsPeriod = changeDiagramsPeriod;
        window.drawTransactionChart = drawTransactionChart;
        window.drawOrdersChart = drawOrdersChart;
        window.drawAmountsChart = drawAmountsChart;
        window.getChartXLabels = getChartXLabels;
    });
</script>
