<head>
    <title>Full screen layout demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php if($block->isEnabledChat()):?>
        <?php echo $block->getHeadScript()?>
    <?php endif;?>
</head>
<body>
<div id="app-container">
    <div id="main-content"></div>
</div>
<?php if($block->isEnabledChat()):?>
    <?php echo $block->getBodyScript()?>
<?php endif;?>
</body>


