<script type="text/javascript">
require.config({
	'*': {
		"ui/form/field.html":"Vnecoms_VendorsProduct/form/field.html",
                "ui/form/element/input":"Vnecoms_VendorsProduct/form/element/input"
	},
	"paths": {
        "Magento_Catalog/js/components/import-handler": "Vnecoms_VendorsProduct/js/components/import-handler",
        "Magento_Catalog/js/components/new-category":"Vnecoms_VendorsProduct/js/components/new-category",
        "Magento_Catalog/js/components/attribute-set-select":"Vnecoms_VendorsProduct/js/components/attribute-set-select",
        "Magento_Catalog/js/components/dynamic-rows-import-custom-options":"Vnecoms_VendorsProduct/js/components/dynamic-rows-import-custom-options",
        "Magento_Catalog/component/file-type-field.js":"Vnecoms_VendorsProduct/component/file-type-field.js",
        "Magento_Catalog/component/select-type-grid.js":"Vnecoms_VendorsProduct/component/select-type-grid.js",
        "Magento_Catalog/component/static-type-container.js":"Vnecoms_VendorsProduct/component/static-type-container.js",
        "Magento_Catalog/component/static-type-input.js":"Vnecoms_VendorsProduct/component/static-type-input.js",
        "Magento_Catalog/component/static-type-select.js":"Vnecoms_VendorsProduct/component/static-type-select.js",
        "Magento_Catalog/component/text-type-field.js":"Vnecoms_VendorsProduct/component/text-type-field.js",
        "Magento_Catalog/js/custom-options-type.js":"Vnecoms_VendorsProduct/js/custom-options-type.js",
        "Magento_CatalogInventory/js/components/use-config-settings":"Vnecoms_VendorsProduct/js/components/use-config-settings",
        "Magento_CatalogInventory/js/components/qty-validator-changer":"Vnecoms_VendorsProduct/js/components/qty-validator-changer",
        "Magento_CatalogInventory/js/components/use-config-min-sale-qty":"Vnecoms_VendorsProduct/js/components/use-config-min-sale-qty",
        "productGallery":"Vnecoms_VendorsProduct/js/product-gallery",
        "baseImage":"Vnecoms_VendorsProduct/catalog/base-image-uploader",
        "Magento_Backend/js/media-uploader":"Vnecoms_VendorsProduct/js/media-uploader",
        "Magento_Variable/variables":"Vnecoms_VendorsProduct/js/components/variables"
        
	}
});
</script>
