<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Vnecoms\Vendors\Block\Vendors\Page\Footer */
?>

<div class="pull-right hidden-xs">
    <b><?php echo __("Version")?></b> <?php echo $block->getVersion();?>
</div>
<?php if($block->getFooterText()):?>
<?php echo $block->getFooterText();?>
<?php else:?>
<strong><?php echo __('Copyright') ?> &copy; 2016 <a href="http://www.vnecoms.com">Vnecoms</a>.</strong> <?php echo __('All rights reserved.') ?>
<?php endif;?>