<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Giftcard\Block\Product\View */
$description = $block->getDescription()
?>
<?php if (!empty($description)): ?>
    <div class="aw-gc-product-form-description">
        <?php /* @noEscape */ echo $block->getDescription() ?>
    </div>
<?php endif; ?>
