<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Tier */
$element = $block->getElement();
?>
<?php $_htmlId      = $block->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $block->getElement()->getClass() ?>
<?php $_htmlName    = $block->getElement()->getName() ?>
<?php $_readonly    = $block->getElement()->getReadonly() ?>

<style type="text/css">
.shipping_flatrate_table .currency-symbol {
    position: absolute;
    margin-top: 5px;
    width: 20px;
    display: block;
    text-align: center;
}
.shipping_flatrate_table .col-price .input-text,
.shipping_flatrate_table .col-free-shipping .input-text{padding-left: 20px;}
</style>
<div class="control">
    <table class="admin__control-table tiers_table shipping_flatrate_table" id="tiers_table">
        <thead>
            <tr>
                <th class="col-identifier required"><?php /* @escapeNotVerified */ echo __('Identifier') ?></th>
                <th class="col-title required"><?php /* @escapeNotVerified */ echo __('Title') ?></th>
                <th class="col-type required"><?php /* @escapeNotVerified */ echo __('Type') ?></th>
                <th class="col-price required"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                <th class="col-free-shipping">
                    <span data-toggle="tooltip" data-original-title="<?php echo __("Minimum order amount for free shipping")?>" style="text-decoration: underline;">
                        <?php /* @escapeNotVerified */ echo __('Free Shipping') ?>
                    </span>
                </th>
                <th class="col-sort-order"><?php /* @escapeNotVerified */ echo __('Sort Order') ?></th>
                <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
            </tr>
        </thead>
        <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
        <tfoot>
            <tr>
                <td class="col-actions-add" colspan="9"><?php echo $block->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
    </table>

<script>
require([
    'mage/template',
    "prototype",
    "mage/adminhtml/form"
], function (mageTemplate) {

//<![CDATA[
var ratesTemplate = '<tr>'
	+ '<td class="col-ideitnfier"><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry validate-xml-identifier" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][identifier]" value="<%- data.identifier %>" id="rate_row_<%- data.index %>_identifier" /></td>'
	+ '<td class="col-title"><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][title]" value="<%- data.title %>" id="rate_row_<%- data.index %>_title" /></td>'
    + '<td class="col-type">'
    + '<select class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][type]" id="rate_row_<%- data.index %>_type">'
    <?php foreach ($block->getMethodTypes() as $_option): ?>
    + '<option value="<?php /* @escapeNotVerified */ echo $_option['value'] ?>"><?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->escapeHtml($_option['label'])) ?></option>'
    <?php endforeach ?>
    + '</select></td>'
    
    + '<td class="col-price"><div class="currency-symbol"><?php echo $block->getBaseCurrencySymbol()?></div><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry validate-number" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][price]" value="<%- data.price %>" id="rate_row_<%- data.index %>_price" /></td>'

    + '<td class="col-free-shipping"><div class="currency-symbol"><?php echo $block->getBaseCurrencySymbol()?></div><input class="input-text admin__control-text validate-number" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][free_shipping]" value="<%- data.free_shipping %>" id="rate_row_<%- data.index %>_free_shipping" /></td>'
    
    + '<td class="col-sort-order"><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry validate-number" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][sort_order]" value="<%- data.sort_order %>" id="rate_row_<%- data.index %>_sort_order" /></td>'
    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="rate_row_<%- data.index %>_delete" />'
    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Shipping Rate')); ?>" type="button" class="btn btn-danger" id="rate_row_<%- data.index %>_delete_button" onclick="return ratesControl.deleteItem(event);">'
    + '<i class="fa fa-trash-o"></i></button></td>'
    + '</tr>';

var ratesControl = {
    template: mageTemplate(ratesTemplate),
    itemsCount: 0,
    addItem : function (identifier,title, type, price, free_shipping, sort_order) {
        var data = {
    		identifier: identifier,
        	title: title,
        	type: type,
        	price: price,
        	free_shipping: free_shipping,
        	sort_order: sort_order,
            index: this.itemsCount++
        };

        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
            bottom : this.template({
                data: data
            })
        });
        $('rate_row_' + data.index + '_type').value = data.type;
        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
        
    },
    disableElement: function(el) {
        el.disabled = true;
        el.addClassName('disabled');
    },
    deleteItem: function(event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
            Element.hide(tr);
            Element.addClassName(tr, 'no-display template');
        }
        return false;
    }
};
<?php foreach ($block->getValues() as $_item): ?>
ratesControl.addItem(
	'<?php /* @escapeNotVerified */ echo isset($_item['identifier'])?$_item['identifier']:'' ?>',
	'<?php /* @escapeNotVerified */ echo isset($_item['title'])?$_item['title']:'' ?>',
	'<?php /* @escapeNotVerified */ echo isset($_item['type'])?$_item['type']:'O' ?>',
	'<?php /* @escapeNotVerified */ echo isset($_item['price'])?$_item['price']:'0' ?>',
	'<?php /* @escapeNotVerified */ echo isset($_item['free_shipping'])?$_item['free_shipping']:'0' ?>',
	'<?php /* @escapeNotVerified */ echo isset($_item['sort_order'])?$_item['sort_order']:'0'?>'
);
<?php endforeach; ?>

window.ratesControl = ratesControl;
//]]>

});
</script>
</div>

