<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_product = $block->getProduct();
$updates = $block->getUpdates();
?>
<?php if(!$updates->count()):?>
    <p><?php echo __("There is no changes.")?></p>
<?php else:?>
<?php foreach($block->getUpdates() as $update):?>
<section class="admin__page-section order-view-account-information">
    <?php $updateData = unserialize($update->getProductData());?>
    <?php $_product->setStoreId($update->getStoreId());?>
    <div class="admin__page-section-title">
        <span class="title"><?php echo __("Store: %1",$update->getStore()->getName())?></span>
    </div>
    <div class="admin__page-section-content">
      <table class="data-table admin__table-primary">
        <thead>
            <tr class="headings">
                <th class="col-attribute"><span><?php echo __("Attribute")?></span></th>
                <th class="col-current-value"><span><?php echo __("Current Value")?></span></th>
                <th class="col-new-value"><span><?php echo __("New Value")?></span></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($updateData as $attributeCode => $value):?>
            <?php $attribute = $block->getProductAttribute($attributeCode)?>
            <?php $currentValue = $block->getProductAttributeValue($_product,$attributeCode);?>
            <?php $newValue = $block->getProductAttributeValue($_product,$attributeCode, $value);?>
            <?php if($currentValue == $newValue) continue;?>
            <tr>
                <td class="col-attribute"><span><strong><?php echo $attributeCode?></strong></span></td>
                <td class="col-current-value"><span><?php echo $currentValue?></span></td>
                <td class="col-new-value"><span><?php echo $newValue?></span></td>
            </tr>
            <?php endforeach;?>
        </tbody>
      </table>
    </div>
</section>
<?php endforeach;?>
<?php endif;?>