<div class="pb-section pb-section-other-4cols" data-bind="attr: {id: sectionId}">
	<div class="pb-text-col pb-text-col1">
	   <?php echo $block->getChildHtml('col1_text')?>
	</div>
	<div class="pb-text-col pb-text-col2">
	   <?php echo $block->getChildHtml('col2_text')?>
	</div>
	<div class="pb-text-col pb-text-col3">
	   <?php echo $block->getChildHtml('col3_text')?>
	</div>
	<div class="pb-text-col pb-text-col4">
	   <?php echo $block->getChildHtml('col4_text')?>
	</div>
	<div class="pb-clearer"></div>
</div>