<!-- User Account: style can be found in dropdown.less -->
<li class="dropdown user-top-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    	<i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <?php foreach($links as $link):?>
            <li><a href="<?php echo $this->getUrl($link['url'])?>" title="<?php echo $link['title']?>"><i class="<?php echo $link['icon_class']?>"></i> <?php echo $link['label']?></a></li>
        <?php endforeach;?>
    	<li class="divider"></li>
    	<?php if($block->canShowBuyerDashboardLink()):?>
    	<li><a href="<?php echo $this->getBuyerDashboardUrl()?>"><i class="fa fa-dashboard fa-fw"></i> <?php echo __("Buyer Dashboard")?></a></li>
    	<?php endif;?>
    	<li><a href="<?php echo $this->getLogoutLink()?>"><i class="fa fa-sign-out fa-fw"></i> <?php echo __("Logout")?></a></li>
    </ul>
</li>