<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


/** @var $block \Magento\Backend\Block\Widget\Form\Container */
?>

<div class="ves-fieldsets">
    <?php $assignedAttributes = $this->getExcludedAttributes();?>
    <?php foreach($this->getFieldsetCollection() as $fieldset):?>
    <fieldset id="fieldset-<?php echo $fieldset->getId();?>" class="fieldset admin__fieldset user-defined" data-fieldset_id="<?php echo $fieldset->getId()?>">
        <legend class="admin__legend legend">
            <span><?php echo $fieldset->getTitle();?></span>
        </legend>
        <div class="fieldset-ctrl"><a href="javascript: void(0);" class="icon icon-edit" onclick="vesEditFieldset(<?php echo $fieldset->getId();?>)"></a><a href="javascript: void(0);" class="icon icon-delete" onclick="vesDeleteFieldset(<?php echo $fieldset->getId();?>)"></a></div>
        <div class="ves-fieldset-content">
            <?php $attributes = $fieldset->getAttributes();?>
            <ul id="sortable<?php echo $fieldset->getId()?>" class="ves-fieldset-attributes" data-fieldset_id="<?php echo $fieldset->getId()?>">
                <?php foreach($attributes as $attribute):?>
                    <?php $assignedAttributes[] = $attribute->getAttributeCode()?>
                    <li id="<?php echo $attribute->getAttributeCode()?>" data-attr_id="<?php echo $attribute->getId()?>"><?php echo $attribute->getFrontendLabel()?></li>
                <?php endforeach;?>
            </ul>
        </div>
     </fieldset>
     <?php endforeach;?>
</div>
<div class="ves-attributes">
    <fieldset class="fieldset admin__fieldset user-defined">
        <legend class="admin__legend legend">
            <span><?php echo __('Available Attributes')?></span>
        </legend>
        <div class="ves-fieldset-content">
            <ul class="ves-fieldset-attributes ves-fieldset-available-attributes">
                <?php foreach($this->getVendorAttributeCollection() as $attribute):?>
                    <?php if(in_array($attribute->getAttributeCode(), $assignedAttributes)) continue;;?>
                    <li id="<?php echo $attribute->getAttributeCode();?>" data-attr_id="<?php echo $attribute->getId()?>"><?php echo $attribute->getFrontendLabel();?></li>
                <?php endforeach;?>
            </ul>
        </div>
    </fieldset>
</div>