<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var $block \Simi\Simicustomize\Block\Adminhtml\Order\Totals\PreorderDeposit */
?>
<tr class="preorder-deposit">
    <td class="label">
        <strong><?= $block->escapeHtml($block->getLabel()) ?></strong>
    </td>
    <td>
        <strong><?= $block->getValue() ?></strong>
    </td>
</tr>
