import React from 'react'
import {defaultStyle} from './Consts'

const Key = props => {
    const color = props.color ? {fill: props.color} : {};
    const style = {...defaultStyle, ...props.style, ...color}
    return (
        <svg xmlns="http://www.w3.org/2000/svg"
                version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 20 20"
                style={style} className={props.className}
                width={20} height={20}>
            <title>key</title>
            <desc>Created with Sketch.</desc>
            <g id="Shape">
                <path fill="#000000" d="M14.5 8h-0.5v-1.5c0-2.481-2.019-4.5-4.5-4.5s-4.5 2.019-4.5 4.5v1.5h-0.5c-0.827 0-1.5 0.673-1.5 1.5v8c0 0.827 0.673 1.5 1.5 1.5h10c0.827 0 1.5-0.673 1.5-1.5v-8c0-0.827-0.673-1.5-1.5-1.5zM6 6.5c0-1.93 1.57-3.5 3.5-3.5s3.5 1.57 3.5 3.5v1.5h-7v-1.5zM15 17.5c0 0.276-0.224 0.5-0.5 0.5h-10c-0.276 0-0.5-0.224-0.5-0.5v-8c0-0.276 0.224-0.5 0.5-0.5h10c0.276 0 0.5 0.224 0.5 0.5v8z" />
            </g>
        </svg>
    )
}

export default Key;



// {/*?xml version="1.0" encoding="utf-8"?*/}
// {/* Generated by IcoMoon.io */}
// <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" width={20} height={20} viewBox="0 0 20 20">
// </svg>
