<div class="error-page">
  <h3><i class="fa fa-warning text-yellow"></i> <?php echo __("Sorry, you need permissions to view this content.")?></h3>
  <strong><?php echo __("Next Step")?></strong>
    <ul>
        <li><span><?php echo __("If you think this is an error, try signing out and signing in again.")?></span></li>
        <li><span><?php echo __("Contact a system administrator or store owner to gain permissions.")?></span></li>
    </ul>
</div>