<div class="error-page">
    <h2 class="headline text-yellow"> 404</h2>
    <div class="error-content">
      <h3><i class="fa fa-warning text-yellow"></i> <?php echo __("Oops! Page not found.")?></h3>
      <p><?php echo __("We could not find the page you were looking for. Meanwhile, you may <a href=\"%1\">return to dashboard</a>.",$this->getDashboardUrl())?></p>
    </div><!-- /.error-content -->
</div><!-- /.error-page -->