<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<aside class="main-sidebar">
    <section class="sidebar">
      <?php echo $block->getChildHtml('menu_before')?>
      <?php /* @escapeNotVerified */ echo $block->renderNavigation($block->getMenuModel(), 0, 12); ?>
      <?php echo $block->getChildHtml('menu_after')?>
    </section>
</aside>