<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<div class="cr-nav-container" id="cr-nav-container">
    
</div>
<?php $step = 0;?>
<div class="cr-container">
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('vendor.form.register.extra')?>
<form class="form" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?php /* @noEscape */ echo $block->getBlockHtml('formkey'); ?>
    <?php if($blockId = $block->getStaticBlockId()):?>
        <div class="vendor-static-container">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($blockId)->toHtml();?>
        </div>
    <?php endif;?>
    
    <?php echo $block->getChildHtml('vendor_register_form_before')?>
    <div class="cr-steps-container">
        <?php if(!$block->isLoggedIn()):?>
        <?php $step++;?>
        <div class="cr-step cr-step-<?php echo $step?>" data-step="<?php echo $step?>">
            <div class="cr-step-title"><?php echo __("Personal Information")?></div>
            <div class="cr-step-content">
                <div class="cr-step-content-col1">
                    <fieldset class="fieldset create info">
                        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
                        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
                        <input type="hidden" name="is_seller" value="1">
                        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                        <?php /*?>
                        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                        <?php endif ?>
                
                        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                        <?php endif ?>
                
                        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                        <?php endif ?>
                        */?>
                    </fieldset>
                </div>
                <div class="cr-step-content-col2">
                    <?php 
                    $html = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cr_step_content_'.$step)->toHtml();
                    echo $html?$html:__("You can add the content here by adding a Static block with id %1", '<strong>cr_step_content_'.$step.'</strong>');
                    ?>
                </div>
            </div>
        </div>
        <?php endif;?>
        
        <?php $step++?>
        <?php $createForm = $block->getChildBlock('new_vendor_create_form')->setStep($step)?>
        <?php echo $createForm->toHtml()?>
        <?php $step = $createForm->getStep();?>
        
        <?php if(!$block->isLoggedIn()):?>
        <div class="cr-step cr-step-<?php echo $step?>" data-step="<?php echo $step?>">
            <div class="cr-step-title"><?php echo __("Login Information")?></div>
            <div class="cr-step-content">
                <div class="cr-step-content-col1">
                    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                        <div class="field required">
                            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                            <div class="control">
                                <input type="email" name="email" autocomplete="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                            <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                            <div class="control">
                                <input type="password" name="password" id="password"
                                       title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                       class="input-text"
                                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                       data-validate="{required:true, 'validate-customer-password':true}"
                                       autocomplete="off">
                                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                                    <div id="password-strength-meter" class="password-strength-meter">
                                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                                        </span>
                                    </div>
                                </div>
                            </div>
                
                        </div>
                        <div class="field confirmation required">
                            <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
                            <div class="control">
                                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                            </div>
                        </div>
                        
                    </fieldset>
                </div>
                <div class="cr-step-content-col2">
                    <?php 
                    $html = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cr_step_content_'.$step)->toHtml();
                    echo $html?$html:__("You can add the content here by adding a Static block with id %1", '<strong>cr_step_content_'.$step.'</strong>');
                    ?>
                </div>
            </div>
        </div>
        <?php endif;?>
    </div>
    <?php echo $block->getChildHtml('vendor_register_form_after')?>
    
    <div class="cr-confirm">
        <?php if($block->isEnableAgreement()):?>
        <div class="field field-vendor-registration">
            <input type="checkbox" id="vendor-registration-agreement" name="vendor_data[vendor_registration_agreement]" value="1" class="input-text vendor-agreement" data-validate="{'validate-one-required-by-name':true}"/><label for="vendor-registration-agreement"><?php echo $block->getAgreementLabel()?></label>
        </div>
        <?php endif;?>
        
        <?php echo $block->getChildHtml('vendor_register_form_additional_info'); ?>
        
    </div>
    
    <?php echo $block->getChildHtml('vendor_register_form_actions_before')?>
    <div class="actions-toolbar">
        <button id="cr-previous-btn" type="button" class="action cr-previous-btn" title="<?php /* @escapeNotVerified */ echo __('Previous Step') ?>"><span><?php /* @escapeNotVerified */ echo __('Previous Step') ?></span></button>
        <button id="cr-next-btn" type="button" class="action primary cr-next-btn" title="<?php /* @escapeNotVerified */ echo __('Next Step') ?>"><span><?php /* @escapeNotVerified */ echo __('Next Step') ?></span></button>
        <button id="cr-submit-btn" type="submit" class="action primary submit cr-submit-btn" title="<?php /* @escapeNotVerified */ echo __('Create Seller Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create Seller Account') ?></span></button>
    </div>
    
</form>
<script>
var CURRENT_STEP = 1;
require([
    'jquery',
    'mage/template',
    'mage/mage'
], function($, mageTemplate){

    var dataForm = $('#form-validate');
    var ignore = false;
    
    dataForm.mage('validation', {
    	validationUrl: '<?php echo $this->getValidationUrl()?>',
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    dataForm.on('submit', function(){
        if(window.CURRENT_STEP < $('.cr-step').size()) {
            if($(this).valid()){
        		setCurrentStep(window.CURRENT_STEP + 1);
            }
            return false;
        }
        return true;
    });
    /**
     * Build Steps Navigation
     */
    function buildStepNav(){
        var stepsNav = $('#cr-nav-container');
        var template = '<li class="cr-nav-step cr-nav-step-<%- stepNo %>"><div class="cr-nav-step-number"><%- stepNo %></div><div class="cr-nav-step-title"><%- title %></div><div class="cr-nav-bar"></div></li>';
        var html = '<ul class="cr-nav cr-nav-'+$('.cr-step').size()+'cols">';
    	$('.cr-step').each(function(){
        	var stepTitle = $(this).children('.cr-step-title').first().html();
        	var navStepTemplate= mageTemplate(template);
        	html += navStepTemplate({title: stepTitle, stepNo: $(this).data('step')});
    	});
    	html += '</ul>';
    	stepsNav.html(html);
    }

    /**
     * Set current step
     */
    function setCurrentStep(step){
        window.CURRENT_STEP = step;
        $('.cr-nav-step.current').removeClass('current');
        $('.cr-nav-step.complete').removeClass('complete');
        $('.cr-step.cr-step-active').removeClass('cr-step-active');
        
        $('.cr-nav-step-'+step).addClass('current');
        $('.cr-step-'+step).addClass('cr-step-active');

        
        for(var i = 1; i < step; i++){
        	$('.cr-nav-step-'+i).addClass('complete');
        }

        var size = $('.cr-step').size();
        if(step == size){
        	$('#cr-next-btn').hide();
        	$('.cr-confirm').addClass('complete');
        	$('#cr-submit-btn').css('display','inline-block');
        }else{
        	$('#cr-next-btn').css('display','inline-block');
        	$('.cr-confirm').removeClass('complete');
        	$('#cr-submit-btn').hide();
        }
        
        if(step == 1){
        	$('#cr-previous-btn').hide();
        }else{
        	$('#cr-previous-btn').css('display','inline-block');
        }
    }

    /**
     * Next step
     */
    function nextStep(){
        var step = window.CURRENT_STEP + 1;
        if(step > $('.cr-step').size()) return;
        var isValid = true;
        $('.cr-step-'+(step-1)).find('input,textarea,select').each(function(){
            if(!$(this).is(":visible")) return true;
            $(this).validation();
            isValid = isValid && $(this).validation('isValid');
        });
        if(!isValid) return;

        setCurrentStep(step);
    }

    /**
     * Previous step
     */
    function prevousStep(){
        var step = window.CURRENT_STEP - 1;
        if(step <=0) return;
        
        setCurrentStep(step);
    }
    
    buildStepNav();

    setCurrentStep(1);

    $('#cr-next-btn').click(function(){
    	nextStep();
    });

    $('#cr-previous-btn').click(function(){
    	prevousStep();
    });

    $('.cr-nav-step-number').click(function(){
        if(!$(this).parent().hasClass('complete')) return;
        setCurrentStep(parseInt($(this).html()));
    });

    
});
</script>
</div>