<div class="col-lg-3 col-md-3 col-sm-6">
    <div class="team-inner">
    	<div class="team-image"><?php echo($block->getFieldHtml('avatar'));?></div>
    	<div class="team-info">
            <?php echo($block->getFieldHtml('name'));?>
            <?php echo($block->getFieldHtml('description'));?>
    		<ul class="socials">
    			<?php echo($block->getFieldHtml('rss'));?>
    			<?php echo($block->getFieldHtml('facebook'));?>
    			<?php echo($block->getFieldHtml('twitter'));?>
    			<?php echo($block->getFieldHtml('google'));?>
    		</ul>
    	</div>
    </div>
</div>