<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Backend\Block\Widget\Tabs */
?>
<?php if (!empty($tabs)): ?>

<div class="ves-nav" data-role="container" id="<?php /* @escapeNotVerified */ echo $block->getId() ?>" data-mage-init='{"tabs":{"openedState":"active"}}'>
    <ul <?php /* @escapeNotVerified */ echo $block->getUiId('tab', $block->getId()) ?> class="<?php /* @escapeNotVerified */ echo $block->getIsHoriz() ? 'tabs-horiz' : 'tabs admin__page-nav-items' ?>">
        <?php foreach ($tabs as $_tab): ?>

            <?php if (!$block->canShowTab($_tab)): continue;  endif; ?>
            <?php $_tabClass = 'tab-item-link ' . $block->getTabClass($_tab) . ' ' . (preg_match('/\s?ajax\s?/', $_tab->getClass()) ? 'notloaded' : '') ?>
            <?php $_tabType = (!preg_match('/\s?ajax\s?/', $_tabClass) && $block->getTabUrl($_tab) != '#') ? 'link' : '' ?>
            <?php $_tabHref = $block->getTabUrl($_tab) == '#' ? '#' . $block->getTabId($_tab) . '_content' : $block->getTabUrl($_tab) ?>

            <li class="ves-nav-item" <?php if ($block->getTabIsHidden($_tab)): ?> style="display:none"<?php endif; ?><?php /* @escapeNotVerified */ echo $block->getUiId('tab', 'item', $_tab->getId()) ?>>
                <a data-toggle="switch" href="<?php /* @escapeNotVerified */ echo $_tabHref ?>" id="<?php /* @escapeNotVerified */ echo $block->getTabId($_tab) ?>" name="<?php /* @escapeNotVerified */ echo $block->getTabId($_tab, false) ?>" title="<?php /* @escapeNotVerified */ echo $block->getTabTitle($_tab) ?>"
                   class="ves-nav-link <?php /* @escapeNotVerified */ echo $_tabClass;?>"
                   data-tab-type="<?php /* @escapeNotVerified */ echo $_tabType;?>"
                   <?php /* @escapeNotVerified */ echo $block->getUiId('tab', 'link', $_tab->getId()) ?>>

                   <span><?php /* @escapeNotVerified */ echo $block->getTabLabel($_tab); ?></span>
                </a>
                <div data-role="content" id="<?php /* @escapeNotVerified */ echo $block->getTabId($_tab) ?>_content" style="display:none;"<?php /* @escapeNotVerified */ echo $block->getUiId('tab', 'content', $_tab->getId()) ?>><?php /* @escapeNotVerified */ echo $block->getTabContent($_tab) ?></div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
require(['jquery',"mage/backend/tabs"], function($){
    $(function() {
        $('#<?php /* @escapeNotVerified */ echo $block->getId() ?>').tabs({
            active: '<?php /* @escapeNotVerified */ echo $block->getActiveTabId() ?>',
            destination: '#<?php /* @escapeNotVerified */ echo $block->getDestElementId() ?>',
            shadowTabs: <?php /* @escapeNotVerified */ echo $block->getAllShadowTabs()?>,
            tabsBlockPrefix: '<?php /* @escapeNotVerified */ echo $block->getId() ?>_',
            tabIdArgument: 'active_tab'
        });
    });
});
</script>
<?php endif; ?>
