<?php


namespace Simi\Simistorelocator\Model;

use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;


class StoreUrlRewriteGenerator implements StoreUrlRewriteGeneratorInterface
{
    /**
     * Entity type code
     */
    const ENTITY_TYPE = 'custom';

    /** @var \Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory */
    public $urlRewriteFactory;

    /**
     * @var StoreUrlPathGeneratorInterface
     */
    public $storeUrlPathGenerator;

    /**
     * Store manager
     *
     * @var StoreManagerInterface
     */
    public $storeManager;

    /**
     * @var \Simi\Simistorelocator\Model\Store
     */
    public $store;

    /**
     * StorePageUrlRewriteGenerator constructor.
     *
     * @param UrlRewriteFactory     $urlRewriteFactory
     * @param StoreUrlPathGeneratorInterface $storeUrlPathGenerator
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        StoreUrlPathGeneratorInterface $storeUrlPathGenerator,
        StoreManagerInterface $storeManager
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->storeManager = $storeManager;
        $this->storeUrlPathGenerator = $storeUrlPathGenerator;
    }

    /**
     * @param \Simi\Simistorelocator\Model\Store $store
     *
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    public function generate(\Simi\Simistorelocator\Model\Store $store)
    {
        $this->store = $store;
        $urls = $this->_generateForAllStores();
        $this->store = null;

        return $urls;
    }

    /**
     * Generate list of urls for default store
     *
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    protected function _generateForAllStores()
    {
        $urls = [];
        foreach ($this->storeManager->getStores() as $store) {
            $urls[] = $this->_createUrlRewrite($store->getStoreId());
        }

        return $urls;
    }

    /**
     * Create url rewrite object
     *
     * @param int $storeId
     * @param int $redirectType
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite
     */
    protected function _createUrlRewrite($storeId, $redirectType = 0)
    {
        return $this->urlRewriteFactory->create()->setStoreId($storeId)
            ->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($this->store->getId())
            ->setRequestPath($this->store->getRewriteRequestPath())
            ->setTargetPath($this->storeUrlPathGenerator->getCanonicalUrlPath($this->store))
            ->setIsAutogenerated(1)
            ->setRedirectType($redirectType);
    }
}
