<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Aheadworks\Giftcard\Block\Customer\Giftcard\Codes */
$giftcardCodes = $block->getCustomerGiftcardCodes();
?>
<?php if (count($giftcardCodes)): ?>
    <div class="aw-giftcard-codes-block">
        <div class="block-title">
            <span><?php echo $block->escapeHtml(__('Your Gift Card codes')) ?></span>
        </div>
        <div class="block-content">
            <div class="box">
                <div class="box-content">
                    <table class="data table-giftcard-codes">
                        <?php foreach ($giftcardCodes as $giftcardCode): ?>
                            <tr>
                                <td class="code">
                                    <?php if ($this->isAccountPage()): ?>
                                        <form action=""
                                              method="post"
                                              data-mage-init='{"awGiftCardManagement":{}}'>
                                            <input type="hidden" name="code" value="<?php /* @noEscape */ echo $giftcardCode->getCode() ?>">
                                            <a href="#"
                                               data-role="aw-giftcard-check-code-action"
                                               data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getCheckCodeUrl()) ?>"
                                               >
                                                <?php echo $block->escapeHtml($giftcardCode->getCode()) ?>
                                            </a>
                                        </form>
                                    <?php else: ?>
                                        <?php echo $block->escapeHtml($giftcardCode->getCode()) ?>
                                    <?php endif; ?>
                                </td>
                                <td class="balance">
                                    <?php /* @noEscape */ echo $block->formatPrice($giftcardCode->getBalance()) ?>
                                </td>
                                <?php if (!$this->isAccountPage()): ?>
                                    <td class="action-apply">
                                        <form action=""
                                              method="post"
                                              data-mage-init='{"awGiftCardManagement":{}}'>
                                            <input type="hidden" name="code" value="<?php /* @noEscape */ echo $giftcardCode->getCode() ?>">
                                            <a href="#"
                                               data-role="aw-giftcard-apply-action"
                                               data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getApplyUrl()) ?>"
                                               >
                                                <?php echo $block->escapeHtml(__('Apply')) ?>
                                            </a>
                                        </form>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

