<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Backend\Block\Widget\Form\Container */
 ?>
<?= /* @escapeNotVerified */ $block->getFormInitScripts() ?>
<?php if ($block->getButtonsHtml('header')): ?>
    <div class="page-form-actions" <?= /* @escapeNotVerified */ $block->getUiId('content-header') ?>><?= $block->getButtonsHtml('header') ?></div>
<?php endif; ?>
<?= $block->getFormHtml() ?>
<?php if ($block->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?= $block->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>

<div id="modal-form" style="display: none">
    <form id="cancel_request_credit" method="post" action="<?php echo $block->getCancelUrl() ?>">
         <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
         <textarea name="reason_cancel" style="width: 100%" rows="10"></textarea>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#cancel_request": {
            "Vnecoms_VendorsCredit/js/modal-form": {}
        }
    }
</script>

<script>
require([
    'jquery',
    'mage/backend/form',
    'mage/backend/validation'
], function($){

    $('#edit_form').form()
        .validation({
            validationUrl: '<?= /* @escapeNotVerified */ $block->getValidationUrl() ?>',
            highlight: function(element) {
                var detailsElement = $(element).closest('details');
                if (detailsElement.length && detailsElement.is('.details')) {
                    var summaryElement = detailsElement.find('summary');
                    if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
                        summaryElement.trigger('click');
                    }
                }
                $(element).trigger('highlight.validate');
            }
        });

});
</script>
<?= /* @escapeNotVerified */ $block->getFormScripts() ?>
