<?php

// @codingStandardsIgnoreFile

/** @var $block \Vnecoms\PdfPro\Block\Adminhtml\Helper\Chooser\Content */
$helper = $block->getHelper();
$currentTemplate = '';
$currentTemplateId = '';
if ($template = $block->getCurrentTemplate())
{
    $currentTemplate = $template->getSku();
    $currentTemplateId = $template->getId();
    $currentTemplateImageUrl = $helper->getBaseUrlMedia($template->getPreviewImage());
}

$templateArray  = $block->getTemplateJson(false);
$index = array_search($currentTemplateId, array_keys($templateArray));
?>
<!--<style>-->
<!--    .pdf_container {-->
<!--        width: 100%;-->
<!--        position: relative;-->
<!--        z-index: 1;-->
<!--        display: block;-->
<!--    }-->
<!--    .pdf_container:after {-->
<!--        clear:both;-->
<!--    }-->
<!--    .pdf_container .owl-carousel {-->
<!--        float:left;-->
<!--        width: 50%;-->
<!--    }-->
<!--</style>-->
<div id="pdf-theme-container" class="pdf_container">
    <input type="hidden" id="template-id"
           name="template_id" value="<?php echo $currentTemplateId ?>" data-form-part="pdfpro_key_form" />
    <div id="base_template_wrapper"
         class="base-template-wrapper">
        <div id="owl_carousel" class="owl-carousel">
            <?php foreach($block->getTemplateJson(false) as $template):?>
                <div
                    template-id="<?php echo $template['id']?>"
                    class="owl-carousel-li<?php if($currentTemplateId == $template['id']) echo ' active' ?>">
                    <img class="lazyOwl"
                         data-src="<?php echo $template['preview_url'] ?>"
                         alt="<?php echo $template['sku'] ?>" />
                </div>
            <?php endforeach;?>
        </div>
    </div>
    <div class="pdf-preview">
        <?php if($currentTemplateId):?>
            <img id="img-preview-image" src="<?php echo $currentTemplateImageUrl?>" width="200px;"/>
            <h2 class="preview-image-label"><?php echo $template['name']?></h2>
        <?php else:?>
            <img id="img-preview-image" class="hidden" src="" width="200px;" />
            <h2 class="hidden preview-image-label">&nbsp;</h2>
            <div class="no-image"><p><?php echo __('Choose a theme')?></p></div>
        <?php endif;?>
    </div>
</div>
<script>
    require('mage/apply/main').apply();
</script>
<script type="text/x-magento-init">
<?php
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode([
        '#base_template_wrapper' => ['Vnecoms_PdfPro/js/easypdf' => [
            'editorIds' => ['pdfpro_key_form_order_template','pdfpro_key_form_invoice_template',
                'pdfpro_key_form_shipment_template','pdfpro_key_form_creditmemo_template'],
            'currentTemplateId' => $currentTemplateId,
            'valueFieldSelector' => '#base_template_wrapper',
            'hiddenTemplateElement' => '[name=template_id]',
            'templateItems' => '.owl-carousel-li',
            'activeItem'    => '.active',
            'ajaxUrl'       => $block->getAjaxUrl(),
            'previewImageId'=> '#img-preview-image',
            'previewImagesJson' => $block->getPreviewImagesJson(),
        ]],
    ]);
    ?>
</script>

<script>
    require([
        "jquery",
        "owlCarousel"
    ], function ($) {
        $('.owl-carousel').owlCarousel({
            lazyLoad : true,
            items: 4,
            lazyEffect : "fade",
            lazyFollow : true,
            navigation : true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:3
                },
                1000:{
                    items:5
                }
            }
        })
    });
</script>