<div class="field field-<?php echo $block->getFieldId()?><?php if($block->isAttributeRequired()):?> required<?php endif;?>">
    <label for="<?php echo $block->getFieldId()?>" class="label">
        <span><?php echo $block->getStoreLabel()?></span>
    </label>

    <div class="control">
        <select id="vendor_region_id" name="<?php echo sprintf($this->getFieldNameFormat(), 'region_id')?>" title="<?php echo $block->getStoreLabel()?>" class="validate-select">
            <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
        </select>
        <input type="text" id="vendor_region" name="<?php echo sprintf($this->getFieldNameFormat(), 'region')?>" value=""  title="<?php echo $block->getStoreLabel()?>" class="<?php echo $block->getFrontendClass()?>" />
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#vendor_country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": true,
                "regionListId": "#vendor_region_id",
                "regionInputId": "#vendor_region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getVendorData('region_id') ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>