<li class="dropdown credit-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-credit-card">&nbsp;</i>
        <?php /*<span class="label label-warning"></span>*/?>
        <?php echo $block->formatCredit($block->getCredit());?>
        <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <?php echo $block->getChildHtml('credit_dropdown_item');?>
    </ul>
</li>