<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Aheadworks\Giftcard\Block\Checkout\Cart\Giftcard */
?>
<div class="block aw-giftcard" id="block-aw-giftcard" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-aw-giftcard-heading" role="heading" aria-level="2">
            <?php echo $block->escapeHtml(__('Gift Card Options')) ?>
        </strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-aw-giftcard-heading">
        <?php echo $block->getChildHtml('giftcard_codes') ?>
        <div id="aw_giftcard__code_info"></div>
        <form id="discount-aw-giftcard-form"
              action=""
              method="post"
              data-mage-init='{"awGiftCardManagement":{}}'>
            <div class="fieldset aw-giftcard">
                <div class="field">
                    <label for="code" class="label">
                        <span><?php echo $block->escapeHtml(__('Enter Gift Card code')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               class="input-text"
                               name="code"
                               placeholder="<?php echo $block->escapeHtml(__('Enter Gift Card code')) ?>"
                               data-validate="{required:true}" />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action apply-aw-giftcard primary"
                                type="submit"
                                value="<?php echo $block->escapeHtml(__('Apply Gift Card code')) ?>"
                                data-role="aw-giftcard-apply-action"
                                data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getActionUrl()) ?>"
                            <span><?php echo $block->escapeHtml(__('Apply Gift Card code')) ?></span>
                        </button>
                    </div>
                    <div class="secondary">
                        <button class="action check-aw-giftcard"
                                type="button"
                                value="<?php echo $block->escapeHtml(__('Check Status and Balance')) ?>"
                                data-role="aw-giftcard-check-code-action"
                                data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getCheckCodeUrl()) ?>">
                            <span><?php echo $block->escapeHtml(__('Check Status and Balance')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>